name: Auto Update StarOTT Premium

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ১ ঘণ্টা পর পর স্বয়ংক্রিয়ভাবে চলবে
  workflow_dispatch:      # ম্যানুয়ালি রান করার বাটন

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install requests pytz

      - name: Run StarOTT Premium Scraper
        run: python starott.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git pull origin main --rebase || true
          git add "starott premium.m3u"
          
          git diff --staged --quiet || git commit -m "StarOTT Premium Auto Update: $(date)"
          git push origin main --force
          
